# Shell variables
# Generated by 'wal'
wallpaper='/home/corbin/.config/wallpaper.png'

# Special
background='#0a0c0e'
foreground='#acbbc5'
cursor='#acbbc5'

# Colors
color0='#0a0c0e'
color1='#9B6C58'
color2='#B2916D'
color3='#386E89'
color4='#4C738C'
color5='#6A798D'
color6='#8F7B89'
color7='#acbbc5'
color8='#788289'
color9='#9B6C58'
color10='#B2916D'
color11='#386E89'
color12='#4C738C'
color13='#6A798D'
color14='#8F7B89'
color15='#acbbc5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
