# Shell variables
# Generated by 'wal'
wallpaper='/home/corbin/Pictures/DSC_0140_edit.jpg'

# Special
background='#0E0E0A'
foreground='#d6d6d7'
cursor='#d6d6d7'

# Colors
color0='#0E0E0A'
color1='#817B78'
color2='#79856A'
color3='#898976'
color4='#CE986E'
color5='#8F908E'
color6='#A7AAA9'
color7='#d6d6d7'
color8='#959596'
color9='#817B78'
color10='#79856A'
color11='#898976'
color12='#CE986E'
color13='#8F908E'
color14='#A7AAA9'
color15='#d6d6d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
