#!/bin/bash

[ -z "$1" ] && exit
echo "Setting wallpaper..."
convert "$1" ~/.config/wallpaper.png
rm -rf ~/.cache/wal
wal -q -i ~/.config/wallpaper.png
notify-send -i ~/.config/wallpaper.png "Wallpaper updated" "$1"
