#!/bin/bash

if pgrep waybar; then
	pkill waybar
	sleep 0.25
	/usr/bin/waybar -c ~/.config/waybar/config-top.json </dev/null &>/dev/null &
	/usr/bin/waybar -c ~/.config/waybar/config-bottom.json </dev/null &>/dev/null &
else
	/usr/bin/waybar -c ~/.config/waybar/config-top.json </dev/null &>/dev/null &
	/usr/bin/waybar -c ~/.config/waybar/config-bottom.json </dev/null &>/dev/null &
fi
